config/routes.rb
Rails.application.routes.draw do

  resources :functions
  resources :agreements
  resources :students
  resources :families
  resources :experiences
  resources :formulas
  resources :products
root 'admin/dashboard#index'

  resources :employees
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match 'reports/vhoja1', via: [:get]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)

   case user.categoria # a_variable is the variable we want to compare
       when 3  # administrador
          can :manage, :all
       when 2  # de Recursos humanos
           can :read, ActiveAdmin::Page, :name =>"Dashboard"
           can [:create,:read,:update,:destroy],  [Employee]
           can [:create,:read,:update,:destroy],  [Family,Experience,Student,Agreement,Function]
       when 1   # usuario empleado
          can :read, ActiveAdmin::Page, :name =>"Dashboard"
          can [:read], [Employee]
          can [:read], [Family,Experience,Student]
        when 4  # director
           can :read, ActiveAdmin::Page, :name =>"Dashboard"
           can [:read], [Employee]
           can [:read], [Family,Experience,Student]
           can [:create,:read,:update,:destroy], [Function]
    end

    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, 
   #      :recoverable, :rememberable, :trackable, :validatable
  devise :ldap_authenticatable, :rememberable, :trackable
end

app/models/agreement.rb
class Agreement < ApplicationRecord
  belongs_to :employee
  belongs_to :admin_user


  validates :fec_inicon, presence: true
  validates :fec_tercon, presence: true
  validates :area, presence: true
  validates :remuneracion, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
mount_uploader :foto, FotoUploader

 belongs_to :admin_user
 has_many :families
 has_many :students
 has_many :experiences
 has_many :agreements
 has_many :functions

  validates :ape_pat, presence: true
  validates :ape_mat, presence: true
  validates :nombres, presence: true
  validates_uniqueness_of :dni

end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :employee
  belongs_to :admin_user
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :employee
  belongs_to :admin_user
end

app/models/formula.rb
class Formula < ApplicationRecord
  belongs_to :admin_user
  belongs_to :product
end

app/models/function.rb
class Function < ApplicationRecord
    belongs_to :employee
    belongs_to :admin_user

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :admin_user
  has_many :formulas

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :employee
  belongs_to :admin_user
end

app/controllers/families_controller.rb
class FamiliesController < InheritedResources::Base

  private

    def family_params
      params.require(:family).permit(:employee_id, :tipo_rela, :admin_user_id)
    end
end

app/controllers/formulas_controller.rb
class FormulasController < InheritedResources::Base

  private

    def formula_params
      params.require(:formula).permit(:nombre, :descripcion, :orden, :obs, :cantidad, :admin_user_id, :product_id, :numero, :acti)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController




  def vhoja1
@nopci=params[:param1]

    respond_to do |format|
      format.html

      format.xlsx{render template: 'reports/hoja1.xlsx.axlsx', xlsx:'personal'}
    end
  end



end

app/helpers/agreements_helper.rb
module AgreementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/families/_form.html.erb
<%= form_with(model: family, local: true) do |form| %>
  <% if family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
      <% family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.text_field :employee_id, id: :family_employee_id %>
  </div>

  <div class="field">
    <%= form.label :tipo_rela %>
    <%= form.text_field :tipo_rela, id: :family_tipo_rela %>
  </div>

  <div class="field">
    <%= form.label :admin_user_id %>
    <%= form.text_field :admin_user_id, id: :family_admin_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Families</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Tipo rela</th>
      <th>Admin user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @families.each do |family| %>
      <tr>
        <td><%= family.employee %></td>
        <td><%= family.tipo_rela %></td>
        <td><%= family.admin_user %></td>
        <td><%= link_to 'Show', family %></td>
        <td><%= link_to 'Edit', edit_family_path(family) %></td>
        <td><%= link_to 'Destroy', family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Family', new_family_path %>

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @family.employee %>
</p>

<p>
  <strong>Tipo rela:</strong>
  <%= @family.tipo_rela %>
</p>

<p>
  <strong>Admin user:</strong>
  <%= @family.admin_user %>
</p>

<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>

app/views/formulas/_form.html.erb
<%= form_with(model: formula, local: true) do |form| %>
  <% if formula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formula.errors.count, "error") %> prohibited this formula from being saved:</h2>

      <ul>
      <% formula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :formula_nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :formula_descripcion %>
  </div>

  <div class="field">
    <%= form.label :orden %>
    <%= form.number_field :orden, id: :formula_orden %>
  </div>

  <div class="field">
    <%= form.label :obs %>
    <%= form.text_field :obs, id: :formula_obs %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.number_field :cantidad, id: :formula_cantidad %>
  </div>

  <div class="field">
    <%= form.label :admin_user_id %>
    <%= form.text_field :admin_user_id, id: :formula_admin_user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :formula_product_id %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :numero, id: :formula_numero %>
  </div>

  <div class="field">
    <%= form.label :acti %>
    <%= form.number_field :acti, id: :formula_acti %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/formulas/edit.html.erb
<h1>Editing Formula</h1>

<%= render 'form', formula: @formula %>

<%= link_to 'Show', @formula %> |
<%= link_to 'Back', formulas_path %>

app/views/formulas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Formulas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Orden</th>
      <th>Obs</th>
      <th>Cantidad</th>
      <th>Admin user</th>
      <th>Product</th>
      <th>Numero</th>
      <th>Acti</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @formulas.each do |formula| %>
      <tr>
        <td><%= formula.nombre %></td>
        <td><%= formula.descripcion %></td>
        <td><%= formula.orden %></td>
        <td><%= formula.obs %></td>
        <td><%= formula.cantidad %></td>
        <td><%= formula.admin_user %></td>
        <td><%= formula.product %></td>
        <td><%= formula.numero %></td>
        <td><%= formula.acti %></td>
        <td><%= link_to 'Show', formula %></td>
        <td><%= link_to 'Edit', edit_formula_path(formula) %></td>
        <td><%= link_to 'Destroy', formula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Formula', new_formula_path %>

app/views/formulas/new.html.erb
<h1>New Formula</h1>

<%= render 'form', formula: @formula %>

<%= link_to 'Back', formulas_path %>

app/views/formulas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @formula.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @formula.descripcion %>
</p>

<p>
  <strong>Orden:</strong>
  <%= @formula.orden %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @formula.obs %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @formula.cantidad %>
</p>

<p>
  <strong>Admin user:</strong>
  <%= @formula.admin_user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @formula.product %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @formula.numero %>
</p>

<p>
  <strong>Acti:</strong>
  <%= @formula.acti %>
</p>

<%= link_to 'Edit', edit_formula_path(@formula) %> |
<%= link_to 'Back', formulas_path %>