config/routes.rb
Rails.application.routes.draw do

  resources :functions
  resources :agreements
  resources :students
  resources :families
  resources :experiences
  resources :formulas
  resources :products
root 'admin/dashboard#index'

  resources :employees
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match 'reports/vhoja1', via: [:get]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)

   case user.categoria # a_variable is the variable we want to compare
       when 3  # administrador
          can :manage, :all
       when 2  # de Recursos humanos
           can :read, ActiveAdmin::Page, :name =>"Dashboard"
           can [:create,:read,:update,:destroy],  [Employee]
           can [:create,:read,:update,:destroy],  [Family,Experience,Student,Agreement,Function]
       when 1   # usuario empleado
          can :read, ActiveAdmin::Page, :name =>"Dashboard"
          can [:read], [Employee]
          can [:read], [Family,Experience,Student]
        when 4  # director
           can :read, ActiveAdmin::Page, :name =>"Dashboard"
           can [:read], [Employee]
           can [:read], [Family,Experience,Student]
           can [:create,:read,:update,:destroy], [Function]
    end

    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, 
   #      :recoverable, :rememberable, :trackable, :validatable
  devise :ldap_authenticatable, :rememberable, :trackable
end

app/models/agreement.rb
class Agreement < ApplicationRecord
  belongs_to :employee
  belongs_to :admin_user


  validates :fec_inicon, presence: true
  validates :fec_tercon, presence: true
  validates :area, presence: true
  validates :remuneracion, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
mount_uploader :foto, FotoUploader

 belongs_to :admin_user
 has_many :families
 has_many :students
 has_many :experiences
 has_many :agreements
 has_many :functions

  validates :ape_pat, presence: true
  validates :ape_mat, presence: true
  validates :nombres, presence: true
  validates_uniqueness_of :dni

end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :employee
  belongs_to :admin_user
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :employee
  belongs_to :admin_user
end

app/models/formula.rb
class Formula < ApplicationRecord
  belongs_to :admin_user
  belongs_to :product
end

app/models/function.rb
class Function < ApplicationRecord
    belongs_to :employee
    belongs_to :admin_user

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :admin_user
  has_many :formulas

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :employee
  belongs_to :admin_user
end

app/controllers/experiences_controller.rb
class ExperiencesController < InheritedResources::Base

  private

    def experience_params
      params.require(:experience).permit(:employee_id, :empresa, :desde, :hasta, :cargo, :obs, :admin_user_id)
    end
end

app/controllers/families_controller.rb
class FamiliesController < InheritedResources::Base

  private

    def family_params
      params.require(:family).permit(:employee_id, :tipo_rela, :admin_user_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController




  def vhoja1
@nopci=params[:param1]

    respond_to do |format|
      format.html

      format.xlsx{render template: 'reports/hoja1.xlsx.axlsx', xlsx:'personal'}
    end
  end



end

app/helpers/agreements_helper.rb
module AgreementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/experiences/_form.html.erb
<%= form_with(model: experience, local: true) do |form| %>
  <% if experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.text_field :employee_id, id: :experience_employee_id %>
  </div>

  <div class="field">
    <%= form.label :empresa %>
    <%= form.text_field :empresa, id: :experience_empresa %>
  </div>

  <div class="field">
    <%= form.label :desde %>
    <%= form.date_select :desde, id: :experience_desde %>
  </div>

  <div class="field">
    <%= form.label :hasta %>
    <%= form.date_select :hasta, id: :experience_hasta %>
  </div>

  <div class="field">
    <%= form.label :cargo %>
    <%= form.text_field :cargo, id: :experience_cargo %>
  </div>

  <div class="field">
    <%= form.label :obs %>
    <%= form.number_field :obs, id: :experience_obs %>
  </div>

  <div class="field">
    <%= form.label :admin_user_id %>
    <%= form.text_field :admin_user_id, id: :experience_admin_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing Experience</h1>

<%= render 'form', experience: @experience %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Experiences</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Empresa</th>
      <th>Desde</th>
      <th>Hasta</th>
      <th>Cargo</th>
      <th>Obs</th>
      <th>Admin user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.employee %></td>
        <td><%= experience.empresa %></td>
        <td><%= experience.desde %></td>
        <td><%= experience.hasta %></td>
        <td><%= experience.cargo %></td>
        <td><%= experience.obs %></td>
        <td><%= experience.admin_user %></td>
        <td><%= link_to 'Show', experience %></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience', new_experience_path %>

app/views/experiences/new.html.erb
<h1>New Experience</h1>

<%= render 'form', experience: @experience %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @experience.employee %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @experience.empresa %>
</p>

<p>
  <strong>Desde:</strong>
  <%= @experience.desde %>
</p>

<p>
  <strong>Hasta:</strong>
  <%= @experience.hasta %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @experience.cargo %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @experience.obs %>
</p>

<p>
  <strong>Admin user:</strong>
  <%= @experience.admin_user %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>